{% set name = "azure-functions" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: c1b498cf48beefe2271ebc454f1a4fb6f587bd97c116e412773854b4c66ad1dc

build:
  number: 0
  skip: true  # [py<313]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    - werkzeug >=3.1.3,<3.2.0

# Please install `azure-functions-durable` to use Durable Functions.
{% set deselect_test = [
  "--deselect=tests/decorators/test_decorators.py::TestFunctionsApp::test_activity_trigger",
  "--deselect=tests/decorators/test_decorators.py::TestFunctionsApp::test_durable_client",
  "--deselect=tests/decorators/test_decorators.py::TestFunctionsApp::test_entity_trigger",
  "--deselect=tests/decorators/test_decorators.py::TestFunctionsApp::test_orchestration_trigger"
]%}
test:
  source_files:
    - tests
  imports:
    - azure.functions
    - azure.functions._thirdparty
    - azure.functions.decorators
    - azure.functions.extension
  requires:
    - pip
    - pytest
    - requests >=2,<3
    - mcp
  commands:
    - pip check
    - pytest -vv  {{ deselect_test | join(" ")}}

about:
  home: https://azure.microsoft.com/en-us/products/functions/
  doc_url: https://learn.microsoft.com/en-us/azure/azure-functions/
  dev_url: https://github.com/Azure/azure-functions-python-library
  summary: Azure Functions for Python
  description: Azure Functions Python SDK
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
